# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PcaPoint(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, x: float=None, y: float=None):
        """
        PcaPoint - a model defined in Swagger

        :param x: The x of this PcaPoint.
        :type x: float
        :param y: The y of this PcaPoint.
        :type y: float
        """
        self.swagger_types = {
            'x': float,
            'y': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y'
        }

        self._x = x
        self._y = y

    @classmethod
    def from_dict(cls, dikt) -> 'PcaPoint':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pca_point of this PcaPoint.
        :rtype: PcaPoint
        """
        return deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """
        Gets the x of this PcaPoint.

        :return: The x of this PcaPoint.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """
        Sets the x of this PcaPoint.

        :param x: The x of this PcaPoint.
        :type x: float
        """

        self._x = x

    @property
    def y(self) -> float:
        """
        Gets the y of this PcaPoint.

        :return: The y of this PcaPoint.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """
        Sets the y of this PcaPoint.

        :param y: The y of this PcaPoint.
        :type y: float
        """

        self._y = y

