# coding: utf-8

from __future__ import absolute_import
from server.models.pca_point import PcaPoint
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PcaPoints(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, points: List[PcaPoint]=None):
        """
        PcaPoints - a model defined in Swagger

        :param points: The points of this PcaPoints.
        :type points: List[PcaPoint]
        """
        self.swagger_types = {
            'points': List[PcaPoint]
        }

        self.attribute_map = {
            'points': 'points'
        }

        self._points = points

    @classmethod
    def from_dict(cls, dikt) -> 'PcaPoints':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pca_points of this PcaPoints.
        :rtype: PcaPoints
        """
        return deserialize_model(dikt, cls)

    @property
    def points(self) -> List[PcaPoint]:
        """
        Gets the points of this PcaPoints.

        :return: The points of this PcaPoints.
        :rtype: List[PcaPoint]
        """
        return self._points

    @points.setter
    def points(self, points: List[PcaPoint]):
        """
        Sets the points of this PcaPoints.

        :param points: The points of this PcaPoints.
        :type points: List[PcaPoint]
        """

        self._points = points

